# -*- coding: utf-8 -*-
"""INFO 450 Final Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wjW50HrxKU8mmokCdrZ-bwGRKGl2xqvz
"""

import pandas as pd
import numpy as np
from pathlib import Path
import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import seaborn as sns

# Load data
CSV_PATH = Path("heart_disease_uci.csv")  # keep CSV in same folder
df_raw = pd.read_csv(CSV_PATH)

# Make  a copy
df = df_raw.copy()
df.columns = df.columns.str.strip().str.lower()


# Treat physiologically impossible zeros as missing
for col in ["trestbps", "chol", "thalch"]:
    if col in df.columns:
        df.loc[df[col] == 0, col] = np.nan

# Convert to appropriate types
if "sex" in df.columns and df["sex"].dtype == "object":
    df["sex"] = df["sex"].map({"Male": 1, "Female": 0}).astype("Int64")

for col in ["fbs", "exang"]:
    if col in df.columns and df[col].dtype == "object":
        df[col] = df[col].map({True: 1, False: 0}).astype("Int64")

for col in ["cp", "restecg", "slope", "thal", "dataset"]:
    if col in df.columns:
        df[col] = df[col].astype("category")

for col in ["age", "trestbps", "chol", "thalch", "oldpeak", "ca", "num"]:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

# Rename
df = df.rename(
    columns={
        "trestbps": "resting_bp",
        "chol": "cholesterol",
        "thalch": "max_hr",
        "num": "disease_class",
    }
)

# Drop non-informative ID
if "id" in df.columns:
    df = df.drop(columns=["id"])

# 3. Missing value report & simple imputation
missing = df.isna().sum().to_frame("n_missing")
missing["pct_missing"] = missing["n_missing"] / len(df)

# Make an imputed copy
df_impute = df.copy()
num_cols = df_impute.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = df_impute.select_dtypes(include=["category"]).columns.tolist()

for col in num_cols:
    df_impute[col].fillna(df_impute[col].median(), inplace=True)

for col in cat_cols:
    df_impute[col].fillna(df_impute[col].mode().iloc[0], inplace=True)

# 4. Figure output directory
FIG_DIR = Path("figures")
FIG_DIR.mkdir(exist_ok=True)

def save_fig(fig, name: str):
    """
    Helper to save a Plotly figure as HTML.
    """
    out_path = FIG_DIR / f"{name}.html"
    fig.write_html(out_path)
    print(f"Saved: {out_path}")

# Univariate analysis – numeric variables
num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = df.select_dtypes(include=["category"]).columns.tolist()

for col in num_cols:
    fig = px.histogram(
        df,
        x=col,
        nbins=30,
        marginal="box",
        title=f"{col} distribution (hist + boxplot)",
    )
    save_fig(fig, f"univariate_hist_{col}")

# Univariate analysis - categorical variables
for col in cat_cols:
    fig = px.histogram(
        df,
        x=col,
        title=f"{col} frequency (categorical)",
    )
    save_fig(fig, f"univariate_freq_{col}")

# Also simple bar charts for binary 0/1 columns
for col in ["sex", "fbs", "exang"]:
    if col in df.columns:
        fig = px.histogram(
            df,
            x=col,
            title=f"{col} frequency (binary)",
        )
        save_fig(fig, f"univariate_freq_{col}")

# Boxplots: continuous vs disease_class
if "disease_class" in df.columns:
    for y in ["age", "resting_bp", "cholesterol", "max_hr", "oldpeak"]:
        if y in df.columns:
            fig = px.box(
                df,
                x="disease_class",
                y=y,
                title=f"{y} by disease_class (boxplot)",
            )
            save_fig(fig, f"box_diseaseclass_{y}")

# Bivariate scatterplots
if {"max_hr", "oldpeak", "disease_class"}.issubset(df.columns):
    fig = px.scatter(
        df,
        x="max_hr",
        y="oldpeak",
        color="disease_class",
        hover_data=[c for c in ["age", "resting_bp", "cholesterol"] if c in df.columns],
        title="Max Heart Rate vs ST Depression (colored by disease_class)",
    )
    save_fig(fig, "scatter_maxhr_oldpeak_by_class")

if {"age", "cholesterol", "disease_class"}.issubset(df.columns):
    fig = px.scatter(
        df,
        x="age",
        y="cholesterol",
        color="disease_class",
        title="Age vs Cholesterol (colored by disease_class)",
    )
    save_fig(fig, "scatter_age_chol_by_class")

# Correlation heatmap
num_df = df.select_dtypes(include=[np.number]).dropna()
if not num_df.empty:
    corr = num_df.corr().round(2)
    heat = go.Figure(
        data=go.Heatmap(
            z=corr.values,
            x=corr.columns,
            y=corr.columns,
            zmin=-1,
            zmax=1,
            colorscale="RdBu",
            colorbar=dict(title="corr"),
        )
    )
    heat.update_layout(title="Feature Correlation Heatmap")
    save_fig(heat, "correlation_heatmap")

# Parallel coordinates plot
pc_cols = [
    c
    for c in ["age", "resting_bp", "cholesterol", "max_hr", "oldpeak", "ca", "disease_class"]
    if c in df.columns
]

if len(pc_cols) >= 4:
    pc_df = df[pc_cols].dropna().copy()
    if not pc_df.empty:
        dimensions = [dict(label=c, values=pc_df[c]) for c in pc_cols]
        pc = go.Figure(
            data=go.Parcoords(
                line=dict(
                    color=pc_df["disease_class"],
                    colorscale="Viridis",
                    showscale=True,
                ),
                dimensions=dimensions,
            )
        )
        pc.update_layout(title="Parallel Coordinates: Key Features by Disease Class")
        save_fig(pc, "parallel_coords_key_features")

plt.figure(figsize=(6,4))

df_model["max_hr_bin"] = pd.cut(df_model["max_hr"], bins=[60,100,120,140,160,200])

sns.countplot(
    data=df_model,
    x="max_hr_bin",
    hue="has_disease",
    palette="viridis"
)

plt.title("Max Heart Rate Distribution by Disease Status")
plt.xlabel("Max Heart Rate Range")
plt.ylabel("Count")
plt.legend(title="Has Disease")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""Modeling"""

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier


from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    roc_curve
)

from imblearn.over_sampling import RandomOverSampler, SMOTE

df_model = df_impute.copy()   #

# Drop rows missing disease_class
df_model = df_model.dropna(subset=["disease_class"])

# Create binary classification label for heart disease
df_model["has_disease"] = (df_model["disease_class"] > 0).astype(int)

# Features & target
X = df_model.drop(columns=["has_disease", "disease_class"])
y = df_model["has_disease"]

# One-hot encode categoricals
X = pd.get_dummies(X, drop_first=True)

print("Final Feature Count:", X.shape[1])
print("Target distribution:\n", y.value_counts())

# Test Train
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y
)

print("\nTraining shape:", X_train.shape)
print("Test shape:", X_test.shape)

#Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# OverSampling
oversamplers = {
    "none": None,

    "random_100": RandomOverSampler(
        sampling_strategy="auto", random_state=42
    ),

    "smote_100": SMOTE(
        sampling_strategy="auto",
        random_state=42,
        k_neighbors=2   # fix for small minority class
    )
}

# Evaluation Function
def evaluate_model(name, y_true, y_pred, y_prob):
    acc = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, zero_division=0)
    rec = recall_score(y_true, y_pred, zero_division=0)
    f1 = f1_score(y_true, y_pred, zero_division=0)
    auc = roc_auc_score(y_true, y_prob)

    print(f"\n=== {name} ===")
    print(f"Accuracy : {acc:.3f}")
    print(f"Precision: {prec:.3f}")
    print(f"Recall   : {rec:.3f}")
    print(f"F1 Score : {f1:.3f}")
    print(f"ROC-AUC  : {auc:.3f}")
    print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))

    return {
        "model": name,
        "accuracy": acc,
        "precision": prec,
        "recall": rec,
        "f1": f1,
        "roc_auc": auc
    }

# Creating the base models + oversampling
results = []

for os_name, os_obj in oversamplers.items():

    print(f"OVERSAMPLER: {os_name}")

    # apply oversampling
    if os_obj is not None:
        X_train_res, y_train_res = os_obj.fit_resample(X_train_scaled, y_train)
    else:
        X_train_res, y_train_res = X_train_scaled, y_train

    print("Class distribution:", pd.Series(y_train_res).value_counts().to_dict())

    # Logistic Regression
    log_reg = LogisticRegression(max_iter=500, solver="liblinear", random_state=42)
    log_reg.fit(X_train_res, y_train_res)

    y_prob_log = log_reg.predict_proba(X_test_scaled)[:, 1]
    y_pred_log = (y_prob_log >= 0.5).astype(int)

    results.append(evaluate_model(f"Logistic (os={os_name})", y_test, y_pred_log, y_prob_log))

    # Decision Tree
    tree = DecisionTreeClassifier(random_state=42)
    tree.fit(X_train_res, y_train_res)

    y_prob_tree = tree.predict_proba(X_test_scaled)[:, 1]
    y_pred_tree = tree.predict(X_test_scaled)

    results.append(evaluate_model(f"DecisionTree (os={os_name})", y_test, y_pred_tree, y_prob_tree))

    # KNN
    knn = KNeighborsClassifier(n_neighbors=5)
    knn.fit(X_train_res, y_train_res)

    y_prob_knn = knn.predict_proba(X_test_scaled)[:, 1]
    y_pred_knn = knn.predict(X_test_scaled)

    results.append(evaluate_model(f"KNN (k=5, os={os_name})", y_test, y_pred_knn, y_prob_knn))

    # Random Forest
    rf = RandomForestClassifier(random_state=42, n_estimators=300,max_depth=None)

    rf.fit(X_train_res, y_train_res)

    y_prob_rf = rf.predict_proba(X_test_scaled)[:, 1]
    y_pred_rf = rf.predict(X_test_scaled)

    results.append(evaluate_model(f"RandomForest (os={os_name})", y_test, y_pred_rf, y_prob_rf))

# ROC curve + Threshold

smote = SMOTE(
    sampling_strategy="auto",
    random_state=42,
    k_neighbors=2
)

X_train_smote, y_train_smote = smote.fit_resample(X_train_scaled, y_train)

log_main = LogisticRegression(
    max_iter=500,
    solver="liblinear",
    random_state=42
)

log_main.fit(X_train_smote, y_train_smote)

# Probabilities
y_prob_main = log_main.predict_proba(X_test_scaled)[:, 1]

# ROC values
fpr, tpr, thresholds = roc_curve(y_test, y_prob_main)

# Best threshold using Youden J
j_scores = tpr - fpr
best_idx = np.argmax(j_scores)
best_thresh = thresholds[best_idx]

print("Best Logistic Threshold:", best_thresh)

# Evaluate using 0.5 and best threshold
evaluate_model("Logistic_SMOTE (threshold=0.5)", y_test,
               (y_prob_main >= 0.5).astype(int), y_prob_main)

evaluate_model("Logistic_SMOTE (best threshold)", y_test,
               (y_prob_main >= best_thresh).astype(int), y_prob_main)

# Tuning for Logistic Regression
log_reg_base = LogisticRegression(max_iter=500, solver="liblinear", random_state=42)

param_grid_log = {
    "C": [0.01, 0.1, 1, 10],
    "penalty": ["l1", "l2"]
}

grid_log = GridSearchCV(log_reg_base, param_grid_log, cv=5, scoring="roc_auc", n_jobs=-1)
grid_log.fit(X_train_smote, y_train_smote)

best_log = grid_log.best_estimator_

y_prob_log_tuned = best_log.predict_proba(X_test_scaled)[:, 1]
y_pred_log_tuned = (y_prob_log_tuned >= best_thresh).astype(int)

eval_log_tuned = evaluate_model("Logistic Tuned", y_test, y_pred_log_tuned, y_prob_log_tuned)

# Tuning for Decision Tree
tree_base = DecisionTreeClassifier(random_state=42)

param_grid_tree = {
    "max_depth": [3, 4, 5, None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4]
}

grid_tree = GridSearchCV(tree_base, param_grid_tree, cv=5, scoring="roc_auc", n_jobs=-1)
grid_tree.fit(X_train_smote, y_train_smote)

best_tree = grid_tree.best_estimator_

y_prob_tree_tuned = best_tree.predict_proba(X_test_scaled)[:, 1]
y_pred_tree_tuned = best_tree.predict(X_test_scaled)

eval_tree_tuned = evaluate_model("Decision Tree Tuned", y_test, y_pred_tree_tuned, y_prob_tree_tuned)

# Tuning for KNN
knn_base = KNeighborsClassifier()

param_grid_knn = {
    "n_neighbors": [3, 5, 7, 9],
    "weights": ["uniform", "distance"],
    "p": [1, 2]
}

grid_knn = GridSearchCV(knn_base, param_grid_knn, cv=5, scoring="roc_auc", n_jobs=-1)
grid_knn.fit(X_train_smote, y_train_smote)

best_knn = grid_knn.best_estimator_

y_prob_knn_tuned = best_knn.predict_proba(X_test_scaled)[:, 1]
y_pred_knn_tuned = best_knn.predict(X_test_scaled)

eval_knn_tuned = evaluate_model("KNN Tuned", y_test, y_pred_knn_tuned, y_prob_knn_tuned)

from sklearn.model_selection import RandomizedSearchCV

rf_base = RandomForestClassifier(random_state=42)

param_dist_rf = {
    "n_estimators": [100, 200, 300, 400, 500],
    "max_depth": [None, 5, 10, 20, 30],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": ["sqrt", "log2"]
}

rf_rand = RandomizedSearchCV(
    rf_base,
    param_dist_rf,
    n_iter=20,               # only try 20 combos
    cv=5,
    scoring="roc_auc",
    n_jobs=-1,
    random_state=42
)

rf_rand.fit(X_train_smote, y_train_smote)

print("Best Random Forest Parameters:", rf_rand.best_params_)

best_rf = rf_rand.best_estimator_

y_prob_rf_tuned = best_rf.predict_proba(X_test_scaled)[:, 1]
y_pred_rf_tuned = best_rf.predict(X_test_scaled)

eval_rf_tuned = evaluate_model(
    "Random Forest Tuned",
    y_test,
    y_pred_rf_tuned,
    y_prob_rf_tuned
)

#Final Summary
tuned_df = pd.DataFrame([
    eval_log_tuned,
    eval_tree_tuned,
    eval_knn_tuned,
    eval_rf_tuned
])

print("TUNED MODEL SUMMARY")
display(tuned_df.sort_values(by="roc_auc", ascending=False))

